version: "3.9"

services:
  back:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: back
    command: python main.py
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis
  db:
    image: postgres:14
    container_name: db
    volumes:
      - pgdata_dev:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env.dev
  redis:
    image: redis:7
    container_name: redis
    volumes:
      - redis_dev:/data
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_HOST_PASSWORD}
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env.dev
    volumes:
      - pgadmin_dev:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped

volumes:
  pgdata_dev:
  pgadmin_dev:
  redis_dev:
